[theme]
primaryColor = "#000000" # Warna utama
backgroundColor = "#004A55" # Warna latar belakang
secondaryBackgroundColor = "#F87D09" # Warna latar belakang sekunder
textColor = "F6F6F6" # Warna teks
font = "Roboto" # Jenis font