[theme]
primaryColor = "#000000" # Warna utama
backgroundColor = "#982B1C" # Warna latar belakang
secondaryBackgroundColor = "#800000" # Warna latar belakang sekunder
textColor = "F2E8C6" # Warna teks
font = "Roboto" # Jenis font