[theme]
primaryColor = "#800000" # Warna utama
backgroundColor = "#F2E8C6" # Warna latar belakang
secondaryBackgroundColor = "#000000" # Warna latar belakang sekunder
textColor = "#000000" # Warna teks
font = "Roboto" # Jenis font